# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba454e914ae4a138d414e66a19e77cb312984073408d73d4122669b055aed9b5caefb38f35f71c4c1fa5aaacb69e64454ad1f70791b108a5e0e77674e24fa947

test:
  secret_key_base: dbffc109320cfdf1b501062c03f7d649c43c735d210d91314ca295a0124a319c738c48adeb003e90628a61630ede0f1aaa7581614c1f93d610ed9048c2cb0159

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
